### PR TITLE
Copy permission bits from template to target #3

### PR DESCRIPTION
**Pull request by sshashank124**
Added functionality for copying a template's permission bits over to the generated target file in case the `permissions` option is not explicitly specified in the respective module.

Also added a test for the new functionality

Have not added the documentation for the changes to the docs yet. I can add it if needed

### CODE REVIEW

**Comment by JakobGM** [comment]
Awesome!

I'll merge it into master after we have finished up the discussion in #3.
- [ ] Trailing comma.
- [ ] Find out if leading bits are of importance for ``pathlib.Path.chmod()``.

**Comment by sshashank124** [comment]
Do you prefer me adding the review changes as a second commit or should I generally squash/rebase all the commits for a PR into a single commit?

**Comment by JakobGM** [comment]
Personally, I prefer additional commits, as it is easier to see what has been changed since the last read-through. It is not a hardly held opinion, though. When we are satisfied, we can use the new "squash and merge" functionality.

**Comment by sshashank124** [comment]
Updated PR based on review comments. Two things to note:

 1. Implemented permissions using `stat.S_IMODE` instead of `& 0o777` as discussed. However, `& 0o777` is still being used in the tests since we are only interested in the last 3 bytes being set properly and sometimes `stat.S_IMODE` can return additional unwanted bits

 2. Will update the docs after finishing changes for the related issue #4, all at once

**Comment by sshashank124** [comment]
I'm done from my side unless you have anything to add

**Comment by JakobGM** [comment]
Alright, then I'll merge it, everything is good!

Sorry for taking so long, I was somewhat unsure if you wanted to add the documentation as a part of this pull request, but it doesn't really matter what order we do it in.

**Pull request merged**
